name: package
on:
  push:
    paths:
      - apium.sh
      - common.sh.in
      - args.in
      - head.in
      - operations/**
      - lib/**
      - pkg/apm/**
      - .github/workflows/package.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v3
        with:
          repository: alemontn/apium
          path: /home/runner/work/apium/apium

      - name: make apium
        run: |
          cd ~/work/apium/apium
          cat head.in common.sh.in args.in lib/*.sh operations/*.sh apium.sh > apium
          chmod +x apium
          sudo install -m0755 ./apium /usr/bin/apium
          mkdir ~/.config/apium
          echo "APIUM_ROOT=~/.local/app" >~/.config/apium/root.conf

      - name: package apium
        run: |
          cd ~/work/apium/apium/pkg
          mkdir ~/out
          apium -v package
          mv out/*.apm ~/out

      - name: upload package
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: ~/out
